version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
#    depends_on:
#      - db
#  db:
#    image: mariadb
#    restart: always
#    environment:
#      MYSQL_DATABASE: evtask
#      MYSQL_USER: evtask
#      MYSQL_PASSWORD: root
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_INITDB_SKIP_TZINFO: 'true'
#      MYSQL_INITDB_ARGS: --init-file /docker-entrypoint-initdb.d/init.sql
#    volumes:
#      - ./data:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - 3307:3306